import type { Localization } from '@better-auth-ui/core';

export const zhLocalization: Localization = {
  auth: {
    account: '账户',
    alreadyHaveAnAccount: '已有账户？',
    confirmPassword: '确认密码',
    confirmPasswordPlaceholder: '请再次输入密码',
    continueWith: '使用 {{provider}} 继续',
    email: '邮箱',
    emailPlaceholder: '请输入邮箱',
    fieldRequired: '此字段为必填项',
    forgotPassword: '忘记密码',
    forgotPasswordLink: '忘记密码？',
    hidePassword: '隐藏密码',
    invalidEmail: '请输入有效的邮箱地址',
    invalidResetPasswordToken: '无效的密码重置令牌',
    name: '姓名',
    namePlaceholder: '请输入姓名',
    needToCreateAnAccount: '需要创建账户？',
    newPassword: '新密码',
    newPasswordPlaceholder: '请输入新密码',
    or: '或',
    password: '密码',
    passwordPlaceholder: '请输入密码',
    passwordResetEmailSent: '密码重置邮件已发送',
    passwordResetSuccess: '密码重置成功',
    passwordsDoNotMatch: '两次输入的密码不一致',
    rememberMe: '记住我',
    tooLong: '最多 {{max}} 个字符',
    tooShort: '至少 {{min}} 个字符',
    rememberYourPassword: '想起密码了？',
    resend: '重新发送',
    resetPassword: '重置密码',
    sendResetLink: '发送重置链接',
    showPassword: '显示密码',
    signIn: '登录',
    signOut: '退出登录',
    signUp: '注册',
    verificationEmailSent: '验证邮件已发送！',
    verifyYourEmail: '请验证您的邮箱',
  },
  settings: {
    account: '账户',
    accountUnlinked: '账户已解绑',
    active: '活跃',
    activeSessions: '活跃会话',
    avatar: '头像',
    currentSession: '当前会话',
    avatarChangedSuccess: '头像修改成功',
    avatarDeletedSuccess: '头像删除成功',
    changeAvatar: '更换头像',
    deleteAvatar: '删除头像',
    link: '绑定',
    linkedAccounts: '已绑定账户',
    linkProvider: '绑定 {{provider}} 账户',
    cancel: '取消',
    copyToClipboard: '复制到剪贴板',
    changeEmail: '修改邮箱',
    changeEmailSuccess: '请检查邮箱确认修改',
    changePassword: '修改密码',
    changePasswordSuccess: '密码修改成功',
    currentPassword: '当前密码',
    currentPasswordPlaceholder: '请输入当前密码',
    dangerZone: '危险操作',
    delete: '删除',
    optional: '可选',
    profileUpdatedSuccess: '资料更新成功',
    revoke: '撤销',
    revokeSession: '撤销会话',
    revokeSessionSuccess: '会话已撤销',
    saveChanges: '保存更改',
    setPassword: '设置密码',
    setPasswordDescription: '您还没有密码。请求重置链接来设置密码。',
    security: '安全',
    settings: '设置',
    time: '时间',
    unlinkProvider: '解绑 {{provider}}',
    updateEmail: '更新邮箱',
    updatePassword: '更新密码',
    uploadAvatar: '上传头像',
    userProfile: '用户资料',
  },
};
