import type { QuestionRow } from './question-table';

export const mockQuestions: QuestionRow[] = [
  {
    id: '1',
    content: 'HTTP 状态码 404 表示什么？',
    type: 'single_choice',
    options: ['Not Found', 'Bad Request', 'Unauthorized', 'Internal Server Error'],
    answer: 0,
    tags: ['HTTP', '网络'],
    status: 'active',
    creatorName: '张三',
    createdAt: '2026-06-10T08:00:00.000Z',
  },
  {
    id: '2',
    content: '以下哪些是 JavaScript 的原始类型？',
    type: 'multiple_choice',
    options: ['string', 'array', 'boolean', 'object', 'number'],
    answer: [0, 2, 4],
    tags: ['JavaScript', '基础'],
    status: 'pending',
    creatorName: '张三',
    createdAt: '2026-06-12T10:30:00.000Z',
  },
  {
    id: '3',
    content: 'TypeScript 是 JavaScript 的超集。',
    type: 'true_false',
    options: null,
    answer: 0,
    tags: ['TypeScript'],
    status: 'active',
    creatorName: '李四',
    createdAt: '2026-06-13T14:00:00.000Z',
  },
  {
    id: '4',
    content: 'HTML 中，____ 标签用于创建超链接。',
    type: 'fill_blank',
    options: null,
    answer: 'a',
    tags: ['HTML', '前端'],
    status: 'rejected',
    creatorName: '张三',
    createdAt: '2026-06-14T09:00:00.000Z',
  },
  {
    id: '5',
    content: '解释 RESTful API 的设计原则，并举例说明。',
    type: 'essay',
    options: null,
    answer: 'RESTful API 的核心原则包括：无状态、统一接口、资源导向...',
    tags: ['API', '架构'],
    status: 'pending',
    creatorName: '李四',
    createdAt: '2026-06-15T11:00:00.000Z',
  },
  {
    id: '6',
    content: 'React 中 useState 返回的第二个值是什么？',
    type: 'fill_blank',
    options: null,
    answer: 'setState',
    tags: ['React', 'Hooks'],
    status: 'active',
    creatorName: '王五',
    createdAt: '2026-06-14T16:00:00.000Z',
  },
  {
    id: '7',
    content: 'CSS 中，以下哪个属性用于设置文字颜色？',
    type: 'single_choice',
    options: ['font-color', 'text-color', 'color', 'foreground'],
    answer: 2,
    tags: ['CSS', '基础'],
    status: 'active',
    creatorName: '王五',
    createdAt: '2026-06-13T09:00:00.000Z',
  },
  {
    id: '8',
    content: '以下哪些是 HTTP 请求方法？',
    type: 'multiple_choice',
    options: ['GET', 'SEND', 'POST', 'FETCH', 'DELETE'],
    answer: [0, 2, 4],
    tags: ['HTTP', '网络'],
    status: 'active',
    creatorName: '张三',
    createdAt: '2026-06-12T14:00:00.000Z',
  },
  {
    id: '9',
    content: '在 JavaScript 中，null == undefined 的结果是 true。',
    type: 'true_false',
    options: null,
    answer: 0,
    tags: ['JavaScript', '基础'],
    status: 'pending',
    creatorName: '李四',
    createdAt: '2026-06-15T08:00:00.000Z',
  },
  {
    id: '10',
    content: '简述虚拟 DOM 的工作原理及其优势。',
    type: 'essay',
    options: null,
    answer: '虚拟 DOM 是真实 DOM 的轻量级 JavaScript 对象表示...',
    tags: ['React', '原理'],
    status: 'pending',
    creatorName: '王五',
    createdAt: '2026-06-14T10:00:00.000Z',
  },
  {
    id: '11',
    content: 'Node.js 中，____ 模块用于操作文件系统。',
    type: 'fill_blank',
    options: null,
    answer: 'fs',
    tags: ['Node.js', '基础'],
    status: 'active',
    creatorName: '李四',
    createdAt: '2026-06-13T11:00:00.000Z',
  },
  {
    id: '12',
    content: 'CSS Flexbox 中，justify-content 的默认值是？',
    type: 'single_choice',
    options: ['center', 'flex-start', 'flex-end', 'space-between'],
    answer: 1,
    tags: ['CSS', '布局'],
    status: 'rejected',
    creatorName: '张三',
    createdAt: '2026-06-12T08:00:00.000Z',
  },
];
