/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteRouteImport } from './routes/teacher/route'
import { Route as StudentRouteRouteImport } from './routes/student/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as TeacherIndexRouteImport } from './routes/teacher/index'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as SettingsPathRouteImport } from './routes/settings/$path'
import { Route as AuthPathRouteImport } from './routes/auth/$path'
import { Route as TeacherSubjectsIndexRouteImport } from './routes/teacher/subjects/index'
import { Route as TeacherQuestionsIndexRouteImport } from './routes/teacher/questions/index'
import { Route as StudentSubjectsIndexRouteImport } from './routes/student/subjects/index'
import { Route as TeacherSubjectsSubjectIdRouteImport } from './routes/teacher/subjects/$subjectId'
import { Route as StudentSubjectsSubjectIdRouteImport } from './routes/student/subjects/$subjectId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as TeacherSubjectsSubjectIdIndexRouteImport } from './routes/teacher/subjects/$subjectId/index'
import { Route as StudentSubjectsSubjectIdIndexRouteImport } from './routes/student/subjects/$subjectId/index'
import { Route as TeacherSubjectsSubjectIdExamsExamIdIndexRouteImport } from './routes/teacher/subjects/$subjectId/exams/$examId/index'
import { Route as StudentSubjectsSubjectIdExamsExamIdIndexRouteImport } from './routes/student/subjects/$subjectId/exams/$examId/index'
import { Route as TeacherSubjectsSubjectIdExamsExamIdSubmissionsIndexRouteImport } from './routes/teacher/subjects/$subjectId/exams/$examId/submissions/index'
import { Route as StudentSubjectsSubjectIdExamsExamIdResultIndexRouteImport } from './routes/student/subjects/$subjectId/exams/$examId/result/index'
import { Route as TeacherSubjectsSubjectIdExamsExamIdSubmissionsSubmissionIdIndexRouteImport } from './routes/teacher/subjects/$subjectId/exams/$examId/submissions/$submissionId/index'

const TeacherRouteRoute = TeacherRouteRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const SettingsPathRoute = SettingsPathRouteImport.update({
  id: '/settings/$path',
  path: '/settings/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathRoute = AuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSubjectsIndexRoute = TeacherSubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherQuestionsIndexRoute = TeacherQuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const StudentSubjectsIndexRoute = StudentSubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => StudentRouteRoute,
} as any)
const TeacherSubjectsSubjectIdRoute =
  TeacherSubjectsSubjectIdRouteImport.update({
    id: '/subjects/$subjectId',
    path: '/subjects/$subjectId',
    getParentRoute: () => TeacherRouteRoute,
  } as any)
const StudentSubjectsSubjectIdRoute =
  StudentSubjectsSubjectIdRouteImport.update({
    id: '/subjects/$subjectId',
    path: '/subjects/$subjectId',
    getParentRoute: () => StudentRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSubjectsSubjectIdIndexRoute =
  TeacherSubjectsSubjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TeacherSubjectsSubjectIdRoute,
  } as any)
const StudentSubjectsSubjectIdIndexRoute =
  StudentSubjectsSubjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudentSubjectsSubjectIdRoute,
  } as any)
const TeacherSubjectsSubjectIdExamsExamIdIndexRoute =
  TeacherSubjectsSubjectIdExamsExamIdIndexRouteImport.update({
    id: '/exams/$examId/',
    path: '/exams/$examId/',
    getParentRoute: () => TeacherSubjectsSubjectIdRoute,
  } as any)
const StudentSubjectsSubjectIdExamsExamIdIndexRoute =
  StudentSubjectsSubjectIdExamsExamIdIndexRouteImport.update({
    id: '/exams/$examId/',
    path: '/exams/$examId/',
    getParentRoute: () => StudentSubjectsSubjectIdRoute,
  } as any)
const TeacherSubjectsSubjectIdExamsExamIdSubmissionsIndexRoute =
  TeacherSubjectsSubjectIdExamsExamIdSubmissionsIndexRouteImport.update({
    id: '/exams/$examId/submissions/',
    path: '/exams/$examId/submissions/',
    getParentRoute: () => TeacherSubjectsSubjectIdRoute,
  } as any)
const StudentSubjectsSubjectIdExamsExamIdResultIndexRoute =
  StudentSubjectsSubjectIdExamsExamIdResultIndexRouteImport.update({
    id: '/exams/$examId/result/',
    path: '/exams/$examId/result/',
    getParentRoute: () => StudentSubjectsSubjectIdRoute,
  } as any)
const TeacherSubjectsSubjectIdExamsExamIdSubmissionsSubmissionIdIndexRoute =
  TeacherSubjectsSubjectIdExamsExamIdSubmissionsSubmissionIdIndexRouteImport.update(
    {
      id: '/exams/$examId/submissions/$submissionId/',
      path: '/exams/$examId/submissions/$submissionId/',
      getParentRoute: () => TeacherSubjectsSubjectIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/teacher': typeof TeacherRouteRouteWithChildren
  '/auth/$path': typeof AuthPathRoute
  '/settings/$path': typeof SettingsPathRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/student/subjects/$subjectId': typeof StudentSubjectsSubjectIdRouteWithChildren
  '/teacher/subjects/$subjectId': typeof TeacherSubjectsSubjectIdRouteWithChildren
  '/student/subjects/': typeof StudentSubjectsIndexRoute
  '/teacher/questions/': typeof TeacherQuestionsIndexRoute
  '/teacher/subjects/': typeof TeacherSubjectsIndexRoute
  '/student/subjects/$subjectId/': typeof StudentSubjectsSubjectIdIndexRoute
  '/teacher/subjects/$subjectId/': typeof TeacherSubjectsSubjectIdIndexRoute
  '/student/subjects/$subjectId/exams/$examId/': typeof StudentSubjectsSubjectIdExamsExamIdIndexRoute
  '/teacher/subjects/$subjectId/exams/$examId/': typeof TeacherSubjectsSubjectIdExamsExamIdIndexRoute
  '/student/subjects/$subjectId/exams/$examId/result/': typeof StudentSubjectsSubjectIdExamsExamIdResultIndexRoute
  '/teacher/subjects/$subjectId/exams/$examId/submissions/': typeof TeacherSubjectsSubjectIdExamsExamIdSubmissionsIndexRoute
  '/teacher/subjects/$subjectId/exams/$examId/submissions/$submissionId/': typeof TeacherSubjectsSubjectIdExamsExamIdSubmissionsSubmissionIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth/$path': typeof AuthPathRoute
  '/settings/$path': typeof SettingsPathRoute
  '/': typeof MainIndexRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/student/subjects': typeof StudentSubjectsIndexRoute
  '/teacher/questions': typeof TeacherQuestionsIndexRoute
  '/teacher/subjects': typeof TeacherSubjectsIndexRoute
  '/student/subjects/$subjectId': typeof StudentSubjectsSubjectIdIndexRoute
  '/teacher/subjects/$subjectId': typeof TeacherSubjectsSubjectIdIndexRoute
  '/student/subjects/$subjectId/exams/$examId': typeof StudentSubjectsSubjectIdExamsExamIdIndexRoute
  '/teacher/subjects/$subjectId/exams/$examId': typeof TeacherSubjectsSubjectIdExamsExamIdIndexRoute
  '/student/subjects/$subjectId/exams/$examId/result': typeof StudentSubjectsSubjectIdExamsExamIdResultIndexRoute
  '/teacher/subjects/$subjectId/exams/$examId/submissions': typeof TeacherSubjectsSubjectIdExamsExamIdSubmissionsIndexRoute
  '/teacher/subjects/$subjectId/exams/$examId/submissions/$submissionId': typeof TeacherSubjectsSubjectIdExamsExamIdSubmissionsSubmissionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/teacher': typeof TeacherRouteRouteWithChildren
  '/auth/$path': typeof AuthPathRoute
  '/settings/$path': typeof SettingsPathRoute
  '/_main/': typeof MainIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/student/subjects/$subjectId': typeof StudentSubjectsSubjectIdRouteWithChildren
  '/teacher/subjects/$subjectId': typeof TeacherSubjectsSubjectIdRouteWithChildren
  '/student/subjects/': typeof StudentSubjectsIndexRoute
  '/teacher/questions/': typeof TeacherQuestionsIndexRoute
  '/teacher/subjects/': typeof TeacherSubjectsIndexRoute
  '/student/subjects/$subjectId/': typeof StudentSubjectsSubjectIdIndexRoute
  '/teacher/subjects/$subjectId/': typeof TeacherSubjectsSubjectIdIndexRoute
  '/student/subjects/$subjectId/exams/$examId/': typeof StudentSubjectsSubjectIdExamsExamIdIndexRoute
  '/teacher/subjects/$subjectId/exams/$examId/': typeof TeacherSubjectsSubjectIdExamsExamIdIndexRoute
  '/student/subjects/$subjectId/exams/$examId/result/': typeof StudentSubjectsSubjectIdExamsExamIdResultIndexRoute
  '/teacher/subjects/$subjectId/exams/$examId/submissions/': typeof TeacherSubjectsSubjectIdExamsExamIdSubmissionsIndexRoute
  '/teacher/subjects/$subjectId/exams/$examId/submissions/$submissionId/': typeof TeacherSubjectsSubjectIdExamsExamIdSubmissionsSubmissionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/auth/$path'
    | '/settings/$path'
    | '/admin/'
    | '/student/'
    | '/teacher/'
    | '/api/auth/$'
    | '/student/subjects/$subjectId'
    | '/teacher/subjects/$subjectId'
    | '/student/subjects/'
    | '/teacher/questions/'
    | '/teacher/subjects/'
    | '/student/subjects/$subjectId/'
    | '/teacher/subjects/$subjectId/'
    | '/student/subjects/$subjectId/exams/$examId/'
    | '/teacher/subjects/$subjectId/exams/$examId/'
    | '/student/subjects/$subjectId/exams/$examId/result/'
    | '/teacher/subjects/$subjectId/exams/$examId/submissions/'
    | '/teacher/subjects/$subjectId/exams/$examId/submissions/$submissionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/$path'
    | '/settings/$path'
    | '/'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/api/auth/$'
    | '/student/subjects'
    | '/teacher/questions'
    | '/teacher/subjects'
    | '/student/subjects/$subjectId'
    | '/teacher/subjects/$subjectId'
    | '/student/subjects/$subjectId/exams/$examId'
    | '/teacher/subjects/$subjectId/exams/$examId'
    | '/student/subjects/$subjectId/exams/$examId/result'
    | '/teacher/subjects/$subjectId/exams/$examId/submissions'
    | '/teacher/subjects/$subjectId/exams/$examId/submissions/$submissionId'
  id:
    | '__root__'
    | '/_main'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/auth/$path'
    | '/settings/$path'
    | '/_main/'
    | '/admin/'
    | '/student/'
    | '/teacher/'
    | '/api/auth/$'
    | '/student/subjects/$subjectId'
    | '/teacher/subjects/$subjectId'
    | '/student/subjects/'
    | '/teacher/questions/'
    | '/teacher/subjects/'
    | '/student/subjects/$subjectId/'
    | '/teacher/subjects/$subjectId/'
    | '/student/subjects/$subjectId/exams/$examId/'
    | '/teacher/subjects/$subjectId/exams/$examId/'
    | '/student/subjects/$subjectId/exams/$examId/result/'
    | '/teacher/subjects/$subjectId/exams/$examId/submissions/'
    | '/teacher/subjects/$subjectId/exams/$examId/submissions/$submissionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
  TeacherRouteRoute: typeof TeacherRouteRouteWithChildren
  AuthPathRoute: typeof AuthPathRoute
  SettingsPathRoute: typeof SettingsPathRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/settings/$path': {
      id: '/settings/$path'
      path: '/settings/$path'
      fullPath: '/settings/$path'
      preLoaderRoute: typeof SettingsPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$path': {
      id: '/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof AuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/subjects/': {
      id: '/teacher/subjects/'
      path: '/subjects'
      fullPath: '/teacher/subjects/'
      preLoaderRoute: typeof TeacherSubjectsIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/questions/': {
      id: '/teacher/questions/'
      path: '/questions'
      fullPath: '/teacher/questions/'
      preLoaderRoute: typeof TeacherQuestionsIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/student/subjects/': {
      id: '/student/subjects/'
      path: '/subjects'
      fullPath: '/student/subjects/'
      preLoaderRoute: typeof StudentSubjectsIndexRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/teacher/subjects/$subjectId': {
      id: '/teacher/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/teacher/subjects/$subjectId'
      preLoaderRoute: typeof TeacherSubjectsSubjectIdRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/student/subjects/$subjectId': {
      id: '/student/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/student/subjects/$subjectId'
      preLoaderRoute: typeof StudentSubjectsSubjectIdRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/subjects/$subjectId/': {
      id: '/teacher/subjects/$subjectId/'
      path: '/'
      fullPath: '/teacher/subjects/$subjectId/'
      preLoaderRoute: typeof TeacherSubjectsSubjectIdIndexRouteImport
      parentRoute: typeof TeacherSubjectsSubjectIdRoute
    }
    '/student/subjects/$subjectId/': {
      id: '/student/subjects/$subjectId/'
      path: '/'
      fullPath: '/student/subjects/$subjectId/'
      preLoaderRoute: typeof StudentSubjectsSubjectIdIndexRouteImport
      parentRoute: typeof StudentSubjectsSubjectIdRoute
    }
    '/teacher/subjects/$subjectId/exams/$examId/': {
      id: '/teacher/subjects/$subjectId/exams/$examId/'
      path: '/exams/$examId'
      fullPath: '/teacher/subjects/$subjectId/exams/$examId/'
      preLoaderRoute: typeof TeacherSubjectsSubjectIdExamsExamIdIndexRouteImport
      parentRoute: typeof TeacherSubjectsSubjectIdRoute
    }
    '/student/subjects/$subjectId/exams/$examId/': {
      id: '/student/subjects/$subjectId/exams/$examId/'
      path: '/exams/$examId'
      fullPath: '/student/subjects/$subjectId/exams/$examId/'
      preLoaderRoute: typeof StudentSubjectsSubjectIdExamsExamIdIndexRouteImport
      parentRoute: typeof StudentSubjectsSubjectIdRoute
    }
    '/teacher/subjects/$subjectId/exams/$examId/submissions/': {
      id: '/teacher/subjects/$subjectId/exams/$examId/submissions/'
      path: '/exams/$examId/submissions'
      fullPath: '/teacher/subjects/$subjectId/exams/$examId/submissions/'
      preLoaderRoute: typeof TeacherSubjectsSubjectIdExamsExamIdSubmissionsIndexRouteImport
      parentRoute: typeof TeacherSubjectsSubjectIdRoute
    }
    '/student/subjects/$subjectId/exams/$examId/result/': {
      id: '/student/subjects/$subjectId/exams/$examId/result/'
      path: '/exams/$examId/result'
      fullPath: '/student/subjects/$subjectId/exams/$examId/result/'
      preLoaderRoute: typeof StudentSubjectsSubjectIdExamsExamIdResultIndexRouteImport
      parentRoute: typeof StudentSubjectsSubjectIdRoute
    }
    '/teacher/subjects/$subjectId/exams/$examId/submissions/$submissionId/': {
      id: '/teacher/subjects/$subjectId/exams/$examId/submissions/$submissionId/'
      path: '/exams/$examId/submissions/$submissionId'
      fullPath: '/teacher/subjects/$subjectId/exams/$examId/submissions/$submissionId/'
      preLoaderRoute: typeof TeacherSubjectsSubjectIdExamsExamIdSubmissionsSubmissionIdIndexRouteImport
      parentRoute: typeof TeacherSubjectsSubjectIdRoute
    }
  }
}

interface MainRouteRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainIndexRoute: MainIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface StudentSubjectsSubjectIdRouteChildren {
  StudentSubjectsSubjectIdIndexRoute: typeof StudentSubjectsSubjectIdIndexRoute
  StudentSubjectsSubjectIdExamsExamIdIndexRoute: typeof StudentSubjectsSubjectIdExamsExamIdIndexRoute
  StudentSubjectsSubjectIdExamsExamIdResultIndexRoute: typeof StudentSubjectsSubjectIdExamsExamIdResultIndexRoute
}

const StudentSubjectsSubjectIdRouteChildren: StudentSubjectsSubjectIdRouteChildren =
  {
    StudentSubjectsSubjectIdIndexRoute: StudentSubjectsSubjectIdIndexRoute,
    StudentSubjectsSubjectIdExamsExamIdIndexRoute:
      StudentSubjectsSubjectIdExamsExamIdIndexRoute,
    StudentSubjectsSubjectIdExamsExamIdResultIndexRoute:
      StudentSubjectsSubjectIdExamsExamIdResultIndexRoute,
  }

const StudentSubjectsSubjectIdRouteWithChildren =
  StudentSubjectsSubjectIdRoute._addFileChildren(
    StudentSubjectsSubjectIdRouteChildren,
  )

interface StudentRouteRouteChildren {
  StudentIndexRoute: typeof StudentIndexRoute
  StudentSubjectsSubjectIdRoute: typeof StudentSubjectsSubjectIdRouteWithChildren
  StudentSubjectsIndexRoute: typeof StudentSubjectsIndexRoute
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentIndexRoute: StudentIndexRoute,
  StudentSubjectsSubjectIdRoute: StudentSubjectsSubjectIdRouteWithChildren,
  StudentSubjectsIndexRoute: StudentSubjectsIndexRoute,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

interface TeacherSubjectsSubjectIdRouteChildren {
  TeacherSubjectsSubjectIdIndexRoute: typeof TeacherSubjectsSubjectIdIndexRoute
  TeacherSubjectsSubjectIdExamsExamIdIndexRoute: typeof TeacherSubjectsSubjectIdExamsExamIdIndexRoute
  TeacherSubjectsSubjectIdExamsExamIdSubmissionsIndexRoute: typeof TeacherSubjectsSubjectIdExamsExamIdSubmissionsIndexRoute
  TeacherSubjectsSubjectIdExamsExamIdSubmissionsSubmissionIdIndexRoute: typeof TeacherSubjectsSubjectIdExamsExamIdSubmissionsSubmissionIdIndexRoute
}

const TeacherSubjectsSubjectIdRouteChildren: TeacherSubjectsSubjectIdRouteChildren =
  {
    TeacherSubjectsSubjectIdIndexRoute: TeacherSubjectsSubjectIdIndexRoute,
    TeacherSubjectsSubjectIdExamsExamIdIndexRoute:
      TeacherSubjectsSubjectIdExamsExamIdIndexRoute,
    TeacherSubjectsSubjectIdExamsExamIdSubmissionsIndexRoute:
      TeacherSubjectsSubjectIdExamsExamIdSubmissionsIndexRoute,
    TeacherSubjectsSubjectIdExamsExamIdSubmissionsSubmissionIdIndexRoute:
      TeacherSubjectsSubjectIdExamsExamIdSubmissionsSubmissionIdIndexRoute,
  }

const TeacherSubjectsSubjectIdRouteWithChildren =
  TeacherSubjectsSubjectIdRoute._addFileChildren(
    TeacherSubjectsSubjectIdRouteChildren,
  )

interface TeacherRouteRouteChildren {
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherSubjectsSubjectIdRoute: typeof TeacherSubjectsSubjectIdRouteWithChildren
  TeacherQuestionsIndexRoute: typeof TeacherQuestionsIndexRoute
  TeacherSubjectsIndexRoute: typeof TeacherSubjectsIndexRoute
}

const TeacherRouteRouteChildren: TeacherRouteRouteChildren = {
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherSubjectsSubjectIdRoute: TeacherSubjectsSubjectIdRouteWithChildren,
  TeacherQuestionsIndexRoute: TeacherQuestionsIndexRoute,
  TeacherSubjectsIndexRoute: TeacherSubjectsIndexRoute,
}

const TeacherRouteRouteWithChildren = TeacherRouteRoute._addFileChildren(
  TeacherRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  StudentRouteRoute: StudentRouteRouteWithChildren,
  TeacherRouteRoute: TeacherRouteRouteWithChildren,
  AuthPathRoute: AuthPathRoute,
  SettingsPathRoute: SettingsPathRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
